# Language Settings
 [en]
   languageName = "English"
   contentDir = "content/en/"
   weight = 1 
  [[en.menu.main]]
    identifier = "Filmmakers"
    name = "The Filmmakers"
    url = "/filmmakers/"
    weight = 1
  [[en.menu.main]]
    identifier = "podcast"
    name = "Inside the Journey"
    url = "/podcast/"
    weight = 2

[es]
  languageName = "Español"
  title = "Massively - Versión Español"
  contentDir = "content/es"
  weight = 2
 [[es.menu.main]]
   identifier = "generic"
   name = "ElDocumental"
   url = "/es/generica/"
   weight = 2
 [[es.menu.main]]
   identifier = "elements"
   name = "LosCreadores"
   url = "/es/elementos/"
   weight = 2
  
# [fr]
#   languageName = "Français"
#   title = "Massively - Version Française"
#   contentDir = "content/fr"
#   [fr.params.navigation]
#     folderName = "essais"