# For Pages the .RelPermalink must match the menu .URL 
# For sections the name/directory must match the menu .Identifier

[[main]]
  identifier = "theFilm"
  name = "TheFilmmakers"
  url = "content/en/"
  weight = 1
[[main]]
  identifier = "Filmmakers"
  name = "TheFilmmakers"
  url = "/filmmakers/"
  weight = 1
[[main]]
  identifier = "podcast"
  name = "podcast"
  url = "/es/podcast/"
  weight = 2