# For Pages the .RelPermalink must match the menu .URL 
# For sections the name/directory must match the menu .Identifier
[[main]]
  identifier = "generic"
  name = "Generic Page"
  url = "/generic/"
  weight = 20
[[main]]
  identifier = "elements"
  name = "Elements Reference"
  url = "/elements/"
  weight = 50