# Open Graph, Twitter, and Meta data settings
title = "Massively"
description = "A free, fully responsive HTML5 + CSS3 site template designed by @ajlkn for HTML5 UP and released for free under the Creative Commons license."
keywords = "HTML, CSS, Template, Creative Commons"
images = ["images/screenshot.png","images/device-screenshots.png","images/tn.png"]

## Set below parameter to define a favicon
# favicon = "favicon.ico"

## Set to change date format
# dateFormat = "2.1.2006"
  
## Set theme-color for mobile devices
## Basic schema settings are light/dark
## Using customMedia will override light/dark settings
[[themeColor]]
  schema = "light"
  content = "#ffffff"
  #customMedia = ""
[[themeColor]]
  schema = "dark"
  content = "#000000"

# Below parameters can be set to override default post settings
[posts]
#     folderName = "posts"
#     pageSize = "6"
#     featuredPost = false
#     paginationPages = 2
#     showFirstLast = false